### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by mershark** [mershark/recipe-app#12]
1. Link to project
[Click here](https://github.com/users/mershark/projects/8/views/1)

2. This project consist of 2 team members @mershark and @aqurds

**Comment by danmainah** [comment]
Hi @mershark and @Aqurds , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

## Highlights
✔️ Set up the Kanban board correctly with all required columns.
✔️ Ensured all tasks from the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) have been added correctly.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
